---
- name: Ensure CHRONY is installed
  ansible.builtin.include_tasks: "install_{{ ansible_os_family | lower }}.yml"
- name: Configuration
  ansible.builtin.include_tasks: "config_{{ ansible_os_family | lower }}.yml"
- name: Ensure chronyd is running (and enabled at boot)
  become: true
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
