---
- name: Configuration of chrnony.conf
  become: true
  ansible.builtin.template:
    src: templates/etc/chrony.conf.j2
    dest: '{{ chrony_config_file }}'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart chronyd
