---
- name: Enable SELinux to permissive
  become: true
  ansible.posix.selinux:
    policy: default
    state: permissive
  listen: Enable SELinux
- name: Relabel files
  become: true
  ansible.builtin.command: fixfiles onboot
  listen: Enable SELinux
- name: Activate SELinux
  become: true
  ansible.builtin.command: selinux-activate
  listen: Enable SELinux
- name: Reboot if required
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
  listen: Enable SELinux
